Repository MTVS-3rd-BanBanMooMani/MeMiLog, pull requests merged in 2024-07, with the labels that each got.

#6 회원 정보 조회, 수정, 삭제 모달 추가
  src/main/resources/css/mydiary.css
  src/main/resources/img/change_profile.png
  src/main/resources/img/default_profile.png
  src/main/resources/view/mydiary.html
Labels: ✨feature

#23 관리자 페이지 신고글 전체 조회 화면 구현 완료
  src/main/resources/documentation/css/reportTotal.css
  src/main/resources/view/admin/admin.html
  src/main/resources/view/admin/post/postDashboard.html
  src/main/resources/view/admin/post/postHidden.html
  src/main/resources/view/admin/post/postTotal.html
  src/main/resources/view/admin/report/reportDashboard.html
  src/main/resources/view/admin/report/reportTotal.html
  src/main/resources/view/admin/user/userBlackList.html
  src/main/resources/view/admin/user/userDashboard.html
  src/main/resources/view/admin/user/userTotal.html
Labels: ✨feature

#26 feature PostMagement/HiddenPost&adminLogin&adminSignUp&adminForgotPW
  src/main/resources/view/404-page.html
  src/main/resources/view/admin/post/postHidden.html
  src/main/resources/view/admin/user/forgot-password.html
  src/main/resources/view/admin/user/login.html
  src/main/resources/view/admin/user/sign-up.html
Labels: ✨feature

#34 공지사항 게시판 완성
  src/main/resources/view/admin/board/noticeBoard.html
Labels: ✨feature

#35 오늘의 주제 수정 페이지 완성
  src/main/resources/documentation/css/adminBoard.css
  src/main/resources/view/admin/board/dailyTopicBoard.html
  src/main/resources/view/admin/board/noticeBoard.html
Labels: ✨feature

#38 refactor home.html for linking css file
  src/main/resources/documentation/css/home.css
  src/main/resources/documentation/img/banner.jpg
  src/main/resources/documentation/img/home-post-photo.jpg
  src/main/resources/documentation/img/material-symbols-light.png
  src/main/resources/view/home.html
Labels: ✨feature, 🏭 refactor

#63 mydiary 페이지 타임리프 적용
  src/main/java/com/banbanmoomani/memilog/controller/MainController.java
  src/main/resources/templates/main/mydiary.html
Labels: ✨ Feature

#65 allview header, footer 분리
  src/main/resources/static/document/css/mainCommon.css
  src/main/resources/templates/main/allview.html
Labels: 🔨 Refactor

#68 Refactor/page/login
  src/main/java/com/banbanmoomani/memilog/DTO/SelfUserDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/UserDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/resources/static/document/css/forgot.css
  src/main/resources/static/document/css/login.css
  src/main/resources/static/document/css/signup.css
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/user/forgot.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: ✨ Feature, 🔨 Refactor

#75 Refactor : login, signup, forgot.css
  src/main/java/com/banbanmoomani/memilog/DTO/SelfUserDTO.java
  src/main/java/com/banbanmoomani/memilog/config/jwt/dummy
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/resources/static/document/css/signup.css
  src/main/resources/templates/user/signup.html
Labels: 🔨 Refactor

#76 - feature user-mapper.xml
  src/main/java/com/banbanmoomani/memilog/config/UserConfig.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/resources/mapper/user-mapper.xml
  src/main/resources/mybatis-config.xml
Labels: ✨ Feature, 🔨 Refactor

#82 Feat: userBlackList - getBlackList
  src/main/java/com/banbanmoomani/memilog/DAO/BlackListMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/StopDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/blacklist/BanListDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/blacklist/BlackListDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/BlackListMapper.xml
  src/main/resources/templates/admin/userBlackList.html
Labels: ✨ Feature

#83 Allview, Mydiary, Post 통합 DTO 생성
  src/main/java/com/banbanmoomani/memilog/DAO/IntegratedMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/IntegratedDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/MissionDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/PostDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/MainController.java
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/java/com/banbanmoomani/memilog/service/MydiaryService.java
  src/main/resources/mapper/IntegratedMapper.xml
  src/main/resources/templates/main/mydiary.html
Labels: ✨ Feature

#85 MainController 수정(모호성 오류 수정)
  src/main/java/com/banbanmoomani/memilog/controller/MainController.java
Labels: ✨ Feature

#86 NoticeBoard - 공지사항 생성
  src/main/java/com/banbanmoomani/memilog/DAO/NoticeMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/NoticeDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/notice/NoticeRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/service/NoticeService.java
  src/main/resources/mapper/NoticeMapper.xml
  src/main/resources/templates/admin/noticeBoard.html
Labels: ✨ Feature

#87 사용자 정보 조회 로직 구현
  src/main/java/com/banbanmoomani/memilog/DAO/IntegratedMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/MydiaryMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/AttachmentDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/CompanionDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/EmotionDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/IntegratedDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/MissionDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/PostDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/ThemeDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/UserDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/java/com/banbanmoomani/memilog/service/MydiaryService.java
  src/main/resources/mapper/IntegratedMapper.xml
  src/main/resources/mapper/MydiaryMapper.xml
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/main/mydiary.html
Labels: ✨ Feature

#88 Feature: login기능
  src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/LoginRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/java/com/banbanmoomani/memilog/service/UserService.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: ✨ Feature

#94 post 조회 로직 수정
  src/main/java/com/banbanmoomani/memilog/DTO/PostDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/resources/mapper/MydiaryMapper.xml
Labels: ✨ Feature

#95 Feature: forgotIdOrPWD, ModifyUser, SMTP emailAuthentication
  build.gradle
  src/main/java/com/banbanmoomani/memilog/DAO/MydiaryMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/user/ForgotPWDRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/user/LoginRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/user/ModifyRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/user/SignUpRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/user/UserDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/user/VerifyRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/config/MailConfig.java
  src/main/java/com/banbanmoomani/memilog/config/dummy
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/java/com/banbanmoomani/memilog/service/MydiaryService.java
  src/main/java/com/banbanmoomani/memilog/service/user/MailServiceInterface.java
  src/main/java/com/banbanmoomani/memilog/service/user/RegisterMailService.java
  src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
  src/main/resources/mapper/MydiaryMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/static/document/js/forgot_password.js
  src/main/resources/static/document/js/signup.js
  src/main/resources/templates/user/forgot.html
  src/main/resources/templates/user/signup.html
Labels: ✨ Feature

#97 Refactor: modifyUser -> dynamic SQL
  src/main/java/com/banbanmoomani/memilog/service/user/RegisterMailService.java
  src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🔨 Refactor

#105 Feat: reportTotal
  src/main/java/com/banbanmoomani/memilog/DAO/BlackListMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/ReportBoardMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/report/RPTCategoryListDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/report/processedPostListDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/report/unProcessedPostListDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/BlackListMapper.xml
  src/main/resources/mapper/ReportBoardMapper.xml
  src/main/resources/templates/admin/dailyTopicBoard.html
  src/main/resources/templates/admin/noticeBoard.html
  src/main/resources/templates/admin/point.html
  src/main/resources/templates/admin/reportTotal.html
  src/main/resources/templates/admin/userBlackList.html
Labels: ✨ Feature

#109 Feat: Admin - DashBoard
  src/main/java/com/banbanmoomani/memilog/DAO/DashBoardMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/dashboard/AgeGroupMemberDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/dashboard/MeMiLogInfoDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/dashboard/ReportedPostDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/DashBoardMapper.xml
  src/main/resources/static/assets/libs/js/dashboard-finance.js
  src/main/resources/static/document/js/userdashboard.js
  src/main/resources/templates/admin/dashboard.html
Labels: ✨ Feature, 🔨 Refactor

#111 Feat: MeMiLogApplication - @EnableScheduling
  src/main/java/com/banbanmoomani/memilog/MeMiLogApplication.java
Labels: ✨ Feature

#114 Feat: Admin Login
  src/main/java/com/banbanmoomani/memilog/DAO/AdminMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/AdminDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/AdminMapper.xml
Labels: ✨ Feature

#117 Feat: Admin 페이지
  src/main/java/com/banbanmoomani/memilog/DAO/AdminMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/MeMiLogInfoMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/admin/dashboard/MeMiLogInfoDiff.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/mapper/MeMiLogInfoMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/admin/reportTotal.html
  src/main/resources/templates/admin/userBlackList.html
Labels: ✨ Feature, 🔨 Refactor

#121 json 파일 변경
  .gitignore
  src/main/java/com/banbanmoomani/memilog/controller/FileController.java
  src/main/java/com/banbanmoomani/memilog/service/FileService.java
Labels: ✨ Feature

#124 Feature: Interceptor 추가
  src/main/java/com/banbanmoomani/memilog/config/StopWatchInterceptor.java
  src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
Labels: ✨ Feature

#125 Refactor
  src/main/java/com/banbanmoomani/memilog/DTO/admin/dashboard/MeMiLogInfoDiff.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/application.yml
  src/main/resources/mapper/BlackListMapper.xml
Labels: 🔨 Refactor

#129 프로필 사진 삭제 구현
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  src/main/java/com/banbanmoomani/memilog/DAO/FileMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/FileController.java
  src/main/java/com/banbanmoomani/memilog/service/FileService.java
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/templates/main/mydiary.html
Labels: ✨ Feature

#130 Feat: post back기능 추가
  src/main/resources/templates/main/postcreate.html
  src/main/resources/templates/main/postupdate.html
Labels: ✨ Feature

#131 Feat: post 사진 추가
  src/main/java/com/banbanmoomani/memilog/DAO/FileMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/FileDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/post/CreateRequestDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/FileService.java
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/templates/main/postcreate.html
Labels: ✨ Feature

#132 Feat: post 사진 추가
  src/main/resources/mapper/FileMapper.xml
Labels: ✨ Feature

#133 사용자 탈퇴 기능 구현
  src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
  src/main/resources/application.yml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/main/mydiary.html
Labels: ✨ Feature

#134 [Admin] 마지막 기능 구현
  src/main/java/com/banbanmoomani/memilog/DAO/BlackListMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/ReportBoardMapper.java
  src/main/java/com/banbanmoomani/memilog/config/StopWatchInterceptor.java
  src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/application.yml
  src/main/resources/mapper/BlackListMapper.xml
  src/main/resources/mapper/ReportBoardMapper.xml
  src/main/resources/templates/admin/login.html
Labels: ✨ Feature, 🔨 Refactor

#135 회원 정보 동적으로 불러올 수 있게 수정
  src/main/java/com/banbanmoomani/memilog/DAO/MydiaryMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/java/com/banbanmoomani/memilog/service/MydiaryService.java
  src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
  src/main/resources/mapper/MydiaryMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#138 로그인 성공 시 로그인 버튼 > 로그아웃 버튼으로 변경
  src/main/resources/static/document/css/layout.css
  src/main/resources/templates/fragments/mainHeader.html
Labels: 🔨 Refactor

#140 Feature: like 기능 구현 - Controller, Service, Mapper
  src/main/java/com/banbanmoomani/memilog/DAO/LikeMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/LikeDTO.java
  src/main/java/com/banbanmoomani/memilog/MeMiLogApplication.java
  src/main/java/com/banbanmoomani/memilog/config/MailConfig.java
  src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/LikeMapper.xml
  src/main/resources/mapper/PostMapper.xml
Labels: ✨ Feature

#141 Feature: 좋아요, 싫어요 Fetch함수 구현
  src/main/resources/static/document/js/missionPost.js
Labels: ✨ Feature

#142 Feat/User 정지 회원 로그인 거부
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
Labels: ✨ Feature

#143 Refactor/inuk
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
Labels: 🔨 Refactor

#144 Feature/page/main
  src/main/java/com/banbanmoomani/memilog/DAO/MissionMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/archivePostDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/todayPostDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/MainController.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/MissionService.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/MissionMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/img/home-left-arrow.png
  src/main/resources/static/document/img/home-right-arrow.png
  src/main/resources/static/document/js/post.js
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/postcreate.html
Labels: ✨ Feature

#145 Feat: post 사진 넘기는 기능, 아카이브 랜덤 기능 추가
  src/main/java/com/banbanmoomani/memilog/controller/MainController.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/main/home.html
Labels: ✨ Feature

#146 Chart Data 로딩 방식 수정
  src/main/java/com/banbanmoomani/memilog/DAO/ChartMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/MissionMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/ChartController.java
  src/main/java/com/banbanmoomani/memilog/service/ChartService.java
  src/main/java/com/banbanmoomani/memilog/service/MissionService.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/ChartMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#148 Feat: post 경로 설정
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/resources/mapper/PostMapper.xml
Labels: 🔨 Refactor

#149 Feature: Report - controller, service, mapper
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/RPTCategoryMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/UserMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/ReportController.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/java/com/banbanmoomani/memilog/service/RPTCategoryService.java
  src/main/java/com/banbanmoomani/memilog/service/user/UserService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/RPTCategoryMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: ✨ Feature

#150 mydiary 모아보기 컨테이너 무한스크롤 구현
  src/main/resources/static/document/css/mydiary.css
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#151 Refactor: 사진 크기 고정
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/css/postview.css
Labels: 🔨 Refactor

#152 Refactor/inuk
  src/main/java/com/banbanmoomani/memilog/controller/FileController.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/templates/main/postupdate.html
Labels: 🔨 Refactor

#153 Refactor/inuk
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/resources/templates/fragments/mainHeader.html
Labels: 🔨 Refactor

#155 Refactor: 신고 글 처리 - 유저 정지 일수 서비스 로직 추가
  src/main/java/com/banbanmoomani/memilog/DAO/ReportBoardMapper.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/ReportBoardMapper.xml
Labels: 🔨 Refactor

#156 Refactor/inuk MyDiary
  src/main/resources/static/document/css/mydiary.css
Labels: 🔨 Refactor

#158 main layout 수정
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/css/layout.css
  src/main/resources/static/document/css/mydiary.css
  src/main/resources/static/document/img/default_profile.png
  src/main/resources/static/document/img/material-symbols-light.png
  src/main/resources/templates/main/home.html
Labels: 🔨 Refactor

#159 Feature/page/main
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/postupdate.html
Labels: ✨ Feature

#160 Feat: post 수정
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/UpdateFileDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/MissionMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/postupdate.html
Labels: ✨ Feature

#162 mydiary CSS 수정
  src/main/resources/static/document/css/layout.css
  src/main/resources/static/document/css/mydiary.css
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#163 Feat: 저장된 post 데이터 타임리프 연동
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/ImageOrderDTO.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/js/post.js
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/postupdate.html
Labels: ✨ Feature

#164 Refactor/inuk Main Title
  src/main/java/com/banbanmoomani/memilog/DAO/MissionMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/MainTitleDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/MainController.java
  src/main/java/com/banbanmoomani/memilog/service/MissionService.java
  src/main/resources/mapper/MissionMapper.xml
  src/main/resources/templates/main/home.html
Labels: 🔨 Refactor

#166 user 영역, main 수정
  src/main/resources/static/document/css/forgot.css
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/css/layout.css
  src/main/resources/static/document/css/login.css
  src/main/resources/static/document/css/signup.css
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/mydiary.html
  src/main/resources/templates/user/forgot.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 🔨 Refactor

#169 Refactor/page/post
  src/main/java/com/banbanmoomani/memilog/DAO/FileMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/FileDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/UpdateFileDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/FileService.java
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/static/document/js/updatepost.js
  src/main/resources/templates/main/postcreate.html
  src/main/resources/templates/main/postupdate.html
Labels: ✨ Feature

#168 메인 레이아웃 재수정
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/css/layout.css
  src/main/resources/templates/main/home.html
Labels: 🔨 Refactor

#170 refactor: emotion js 수정
  src/main/resources/static/document/js/post.js
  src/main/resources/templates/main/postcreate.html
Labels: 🔨 Refactor

#171 Feature: .jar 파일 배포를 위한 application.yml 및 경로 수정
  src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
  src/main/java/com/banbanmoomani/memilog/service/FileService.java
  src/main/resources/application.yml
  src/main/resources/templates/main/home.html
Labels: ✨ Feature

#172 Refactor/inuk Fragment 경로 수정
  .github/workflows/gradle.yml
  src/main/java/com/banbanmoomani/memilog/config/WebConfiguration.java
  src/main/resources/templates/admin/dailyTopicBoard.html
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/noticeBoard.html
  src/main/resources/templates/admin/point.html
  src/main/resources/templates/admin/reportTotal.html
  src/main/resources/templates/admin/userBlackList.html
  src/main/resources/templates/main/allview.html
  src/main/resources/templates/main/mydiary.html
  src/main/resources/templates/main/postcreate.html
  src/main/resources/templates/main/postupdate.html
  src/main/resources/templates/main/postview.html
  src/main/resources/templates/user/forgot.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: 🔨 Refactor

#173 allview layout 수정
  src/main/resources/static/document/css/allview.css
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/css/layout.css
  src/main/resources/static/document/css/mydiary.css
  src/main/resources/static/document/css/postview.css
  src/main/resources/static/document/css/searchbar.css
  src/main/resources/static/document/js/missionPost.js
  src/main/resources/templates/fragments/mainHeader.html
Labels: 🔨 Refactor

#177 게시물 상세보기 모달 수정
  src/main/resources/static/document/css/postview.css
  src/main/resources/templates/main/postview.html
Labels: 🔨 Refactor

#178 게시글 작성 화면 CSS 수정
  src/main/resources/static/document/css/layout.css
  src/main/resources/static/document/css/post.css
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/main/postcreate.html
Labels: 🔨 Refactor

#179 신고 모달 레이아웃 수정
  src/main/resources/static/document/css/postview.css
Labels: 🔨 Refactor

#181 Refactor/page/post
  path/to/your/upload/dir/KakaoTalk_20240714_134931147.jpg
  path/to/your/upload/dir/KakaoTalk_20240714_134931147_01.jpg
  src/main/java/com/banbanmoomani/memilog/DAO/FileMapper.java
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/DTO/ImageOrderDTO.java
  src/main/java/com/banbanmoomani/memilog/DTO/UpdateFileDTO.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/FileService.java
  src/main/java/com/banbanmoomani/memilog/service/FileStorageService.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/static/document/js/updatepost.js
  src/main/resources/templates/main/postupdate.html
Labels: 🔨 Refactor

#182 Refactor/inuk
  path/to/your/upload/dir/KakaoTalk_20240724_134106151_02.jpg
  src/main/resources/templates/admin/login.html
Labels: 🔨 Refactor

#183 mydiary page에서 사진 클릭 시 상세보기 모달 열리는 기능 추가
  src/main/resources/mapper/MydiaryMapper.xml
  src/main/resources/static/document/css/home.css
  src/main/resources/static/document/css/mydiary.css
  src/main/resources/static/document/css/postview.css
  src/main/resources/static/document/js/mydiary.js
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#185 게시글 상세보기 모달에서 수정, 삭제 기능 추가
  src/main/resources/mapper/MydiaryMapper.xml
  src/main/resources/static/document/css/mydiary.css
  src/main/resources/static/document/js/mydiary.js
Labels: 🔨 Refactor

#186 Refactor/page/main
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/resources/templates/main/home.html
  src/main/resources/templates/main/postcreate.html
  src/main/resources/templates/main/postupdate.html
Labels: 🔨 Refactor

#188 Feat: 삭제 부분 리로드추가
  src/main/resources/templates/main/home.html
Labels: ✨ Feature

#191 Refactor/page/main
  src/main/java/com/banbanmoomani/memilog/controller/MissionController.java
  src/main/resources/static/document/js/missionPost.js
  src/main/resources/templates/main/allview.html
  src/main/resources/templates/main/home.html
Labels: 🔨 Refactor

#194 refactor: main js 분리 리팩토링
  src/main/resources/static/document/js/home.js
  src/main/resources/templates/main/home.html
Labels: 🔨 Refactor

#195 Feat: post 작성 1개 기능 추가
  src/main/java/com/banbanmoomani/memilog/DAO/PostMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/PostController.java
  src/main/java/com/banbanmoomani/memilog/service/PostService.java
  src/main/resources/mapper/PostMapper.xml
Labels: ✨ Feature

#196 Refactor/page/mydiary
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/resources/static/document/js/mydiary.js
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#197 Feat: 충돌 해결
  src/main/resources/mapper/PostMapper.xml
Labels: 🐞 BugFix

#200 Feat: 기본 사진 추가
  src/main/resources/static/document/img/free-icon-add-image-1330259.png
  src/main/resources/templates/main/postcreate.html
Labels: ✨ Feature

#203 Feat: 기본 사진 리팩토링
  src/main/resources/static/document/img/122.png
  src/main/resources/templates/main/postcreate.html
Labels: 🔨 Refactor

#205 Refactor: 미션 상세 페이지 리팩토링
  src/main/resources/static/document/js/allviewModal.js
Labels: 🔨 Refactor

#207 Refactor: 로그인 시 모달 창 나오게 리팩토링
  src/main/java/com/banbanmoomani/memilog/controller/UserController.java
  src/main/resources/static/document/js/home.js
Labels: 🔨 Refactor

#210 Refactor/error
  src/main/java/com/banbanmoomani/memilog/config/CustomErrorController.java
  src/main/java/com/banbanmoomani/memilog/config/StopWatchInterceptor.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/resources/templates/404-page.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/error/error.html
Labels: 🔨 Refactor

#211 Refactor/error
  src/main/java/com/banbanmoomani/memilog/controller/FileController.java
  src/main/java/com/banbanmoomani/memilog/controller/MydiaryController.java
  src/main/resources/static/document/js/mydiary.js
  src/main/resources/templates/main/mydiary.html
Labels: 🔨 Refactor

#212 Refactor: Admin DashBoard
  src/main/java/com/banbanmoomani/memilog/DAO/MeMiLogInfoMapper.java
  src/main/java/com/banbanmoomani/memilog/controller/AdminController.java
  src/main/java/com/banbanmoomani/memilog/service/AdminService.java
  src/main/resources/mapper/DashBoardMapper.xml
Labels: 🔨 Refactor
